// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type BaseResponse struct {
	Code int64       `json:"code"`
	Msg  string      `json:"msg"`
	Time int64       `json:"time"`
	Data interface{} `json:"data"`
}

type CreateSubUserReq struct {
	Username          string `json:"username"`
	Password          string `json:"password"`
	PopId             string `json:"pop_id"`
	UploadRateLimit   int64  `json:"upload_rate_limit,default=655360"`
	DownloadRateLimit int64  `json:"download_rate_limit,default=1310720"`
	MaxBandwidthLimit int64  `json:"max_bandwidth_limit,default=13107200"`
	TotalTrafficLimit int64  `json:"total_traffic_limit,default=1073741824000"`
}

type DeleteSubUserReq struct {
	Username string `json:"username"`
}

type ListPopsResponse struct {
	Pops []*Pop `json:"pops"`
}

type ListSubUserResponse struct {
	Users []*SubUser `json:"sub_users"`
}

type LoginByGoogleRequest struct {
	Credential  string `json:"credential,optional"`
	AccessToken string `json:"access_token,optional"`
	InviteCode  string `json:"invite_code,optional"`
}

type LoginByGoogleResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserId       string `json:"user_id"`
	Email        string `json:"email"`
	Role         string `json:"role"`
	InviteCode   string `json:"invite_code"`
	ExpiresAt    int64  `json:"expires_at"`
}

type LoginRequest struct {
	UserId     string `json:"user_id"`
	Password   string `json:"password,optional"`
	VerifyCode string `json:"verify_code,optional"`
	InviteCode string `json:"invite_code,optional"`
}

type LoginResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserId       string `json:"user_id"`
	Email        string `json:"email"`
	Role         string `json:"role"`
	InviteCode   string `json:"invite_code"`
	ExpiresAt    int64  `json:"expires_at"`
}

type Pop struct {
	Name         string `json:"name"`
	ID           string `json:"id"`
	Area         string `json:"area"`
	Socks5Server string `json:"socks5_server"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserId       string `json:"user_id"`
	Role         string `json:"role"`
	ExpiresAt    int64  `json:"expires_at"`
}

type ResetPasswordRequest struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	VerifyCode string `json:"verify_code"` //验证码
}

type ResetPasswordResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserId       string `json:"user_id"`
	Role         string `json:"role"`
	ExpiresAt    int64  `json:"expires_at"`
}

type SendEmailCodeRequest struct {
	Email     string `json:"email"`
	Purpose   int64  `json:"purpose"`
	PointJson string `json:"point_json"`
}

type SendEmailCodeResponse struct {
}

type SubUser struct {
	Username          string `json:"username"`
	Password          string `json:"password"`
	ServerAddress     string `json:"server_address"`
	TotalTrafficLimit int64  `json:"total_traffic_limit"`
	CurrentTraffic    int64  `json:"current_traffic"`
	MaxBandwidthLimit int64  `json:"max_bandwidth_limit"`
	UploadRateLimit   int64  `json:"upload_rate_limit"`
	DownloadRateLimit int64  `json:"download_rate_limit"`
	CreateTime        int64  `json:"create_time"`
	Status            string `json:"status"`
}

type TrafficLimit struct {
	StartTime    int64 `json:"start_time"`
	EndTime      int64 `json:"end_time"`
	TotalTraffic int64 `json:"total_traffic,default=1073741824000"`
}

type UserExistsReq struct {
	Email string `json:"email"`
}

type UserExistsResp struct {
	Exists bool `json:"exists"`
}

type UserRegisterReq struct {
	Email      string `json:"email"`
	Password   string `json:"password,optional"`
	InviteCode string `json:"invite_code,optional"` // 邀请码
	VerifyCode string `json:"verify_code"`          //验证码
}

type UserRegisterResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserId       string `json:"user_id"`
	Role         string `json:"role"`
	ExpiresAt    int64  `json:"expires_at"`
}
