// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type AllStatsPer5MinReq struct {
	Minutes int32 `form:"minutes"`
}

type AllStatsPerDayReq struct {
	Days int32 `form:"days"`
}

type AllStatsPerHourReq struct {
	Hours int32 `form:"hours"`
}

type BaseResponse struct {
	Code int64       `json:"code"`
	Msg  string      `json:"msg"`
	Time int64       `json:"time"`
	Data interface{} `json:"data"`
}

type CreateSubUserReq struct {
	Username          string `json:"username"`
	Password          string `json:"password"`
	PopId             string `json:"pop_id"`
	UploadRateLimit   int64  `json:"upload_rate_limit,default=655360"`
	DownloadRateLimit int64  `json:"download_rate_limit,default=1310720"`
	MaxBandwidthLimit int64  `json:"max_bandwidth_limit,default=13107200"`
	TotalTrafficLimit int64  `json:"total_traffic_limit,default=1073741824000"`
}

type DeleteSubUserReq struct {
	Username string `json:"username"`
}

type DeprecatedSubUserReq struct {
	Username string `json:"username"`
}

type EditSubUserLimitReq struct {
	Username          string `json:"username"`
	MaxBandwidthLimit *int64 `json:"max_bandwidth_limit,optional"`
	TotalTrafficLimit *int64 `json:"total_traffic_limit,optional"`
}

type GetStatSummaryResponse struct {
	TotalTrafficLimit     int64         `json:"total_traffic_limit"`
	TotalTrafficAllocated int64         `json:"total_traffic_allocated"`
	TrafficUsed           int64         `json:"total_bandwidth_allocated"`
	CurrentBandwidth      int64         `json:"current_bandwidth"`
	TopBandwidth          int           `json:"top_bandwidth"`
	SubUserCount          *SubUserCount `json:"subuser_count"`
	MaxBandwidthLimit     int64         `json:"max_bandwidth_limit"`
	MaxBandwidthAllocated int64         `json:"max_bandwidth_allocated"`
}

type GetSubUserUsageResponse struct {
	SubUsers []*SubUserUsage `json:"sub_users"`
}

type GetTotalQuotaResponse struct {
	TotalBandwidthLimit     int64 `json:"total_bandwidth_limit"`
	TotalTrafficLimit       int64 `json:"total_traffic_limit"`
	TotalBandwidthAllocated int64 `json:"total_bandwidth_allocated"`
	TotalTrafficAllocated   int64 `json:"total_traffic_allocated"`
	SubUserCount            int64 `json:"sub_user_count"`
}

type ListDeprecatedSubUserReq struct {
	Start int `form:"start"`
	End   int `form:"end"`
}

type ListDeprecatedSubUserResponse struct {
	Users []*SubUser `json:"sub_users"`
	Total int        `json:"total"`
}

type ListPopsResponse struct {
	Pops []*Pop `json:"pops"`
}

type ListSubUserReq struct {
	Start int `form:"start"`
	End   int `form:"end"`
}

type ListSubUserResponse struct {
	Users []*SubUser `json:"sub_users"`
	Total int        `json:"total"`
}

type LoginByGoogleRequest struct {
	Credential  string `json:"credential,optional"`
	AccessToken string `json:"access_token,optional"`
	InviteCode  string `json:"invite_code,optional"`
}

type LoginByGoogleResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserId       string `json:"user_id"`
	Email        string `json:"email"`
	Role         string `json:"role"`
	InviteCode   string `json:"invite_code"`
	ExpiresAt    int64  `json:"expires_at"`
}

type LoginRequest struct {
	UserId     string `json:"user_id"`
	Password   string `json:"password,optional"`
	VerifyCode string `json:"verify_code,optional"`
	InviteCode string `json:"invite_code,optional"`
}

type LoginResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserId       string `json:"user_id"`
	Email        string `json:"email"`
	Role         string `json:"role"`
	InviteCode   string `json:"invite_code"`
	ExpiresAt    int64  `json:"expires_at"`
}

type Pop struct {
	Name         string `json:"name"`
	ID           string `json:"id"`
	Area         string `json:"area"`
	CountryCode  string `json:"country_code"`
	Socks5Server string `json:"socks5_server"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserId       string `json:"user_id"`
	Role         string `json:"role"`
	ExpiresAt    int64  `json:"expires_at"`
}

type ResetPasswordRequest struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	VerifyCode string `json:"verify_code"` //验证码
}

type ResetPasswordResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserId       string `json:"user_id"`
	Role         string `json:"role"`
	ExpiresAt    int64  `json:"expires_at"`
}

type SendEmailCodeRequest struct {
	Email     string `json:"email"`
	Purpose   int64  `json:"purpose"`
	PointJson string `json:"point_json"`
}

type SendEmailCodeResponse struct {
}

type StatPoint struct {
	Timestamp int64 `json:"timestamp"`
	Bandwidth int64 `json:"bandwidth"`
	Traffic   int64 `json:"traffic'`
}

type StatsResp struct {
	Stats []*StatPoint `json:"stats"`
}

type SubUser struct {
	Username          string `json:"username"`
	Password          string `json:"password"`
	ServerAddress     string `json:"server_address"`
	TotalTrafficLimit int64  `json:"total_traffic_limit"`
	CurrentTraffic    int64  `json:"current_traffic"`
	MaxBandwidthLimit int64  `json:"max_bandwidth_limit"`
	UploadRateLimit   int64  `json:"upload_rate_limit"`
	DownloadRateLimit int64  `json:"download_rate_limit"`
	CreateTime        int64  `json:"create_time"`
	DeprecatedTime    int64  `json:"deprecated_time"`
	Status            string `json:"status"`
	StartTime         int64
	EndTime           int64
}

type SubUserCount struct {
	Active     int `json:"active"`
	Stop       int `json:"stop"`
	Deprecated int `json:"deprecated"`
}

type SubUserUsage struct {
	Username          string `json:"user_name"`
	MaxBandwidth      int64  `json:"max_bandwidth"`
	CurrentBandwidth  int64  `json:"current_bandwidth"`
	TotalTrafficLimit int64  `json:"total_traffic_limit"`
	TrafficUsed       int64  `json:"traffic_used"`
}

type TrafficLimit struct {
	StartTime    int64 `json:"start_time"`
	EndTime      int64 `json:"end_time"`
	TotalTraffic int64 `json:"total_traffic,default=1073741824000"`
}

type UpdateSubUserStatusReq struct {
	Username string `json:"username"`
	Status   string `json:"status"`
}

type UserExistsReq struct {
	Email string `json:"email"`
}

type UserExistsResp struct {
	Exists bool `json:"exists"`
}

type UserRegisterReq struct {
	Email      string `json:"email"`
	Password   string `json:"password,optional"`
	InviteCode string `json:"invite_code,optional"` // 邀请码
	VerifyCode string `json:"verify_code"`          //验证码
}

type UserRegisterResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserId       string `json:"user_id"`
	Role         string `json:"role"`
	ExpiresAt    int64  `json:"expires_at"`
}

type UserStats5PerMinReq struct {
	Username string `form:"username"`
	Minutes  int32  `form:"minutes"`
}

type UserStatsPerDayReq struct {
	Username string `form:"username"`
	Days     int32  `form:"days"`
}

type UserStatsPerHourReq struct {
	Username string `form:"username"`
	Hours    int32  `form:"hours"`
}
