// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	auth "titan-ipweb/internal/handler/auth"
	"titan-ipweb/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Header, serverCtx.UserAgent, serverCtx.Auth},
			[]rest.Route{
				{
					// 创建子用户
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: CreateSubUserHandler(serverCtx),
				},
				{
					// 删除子用户
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: DeleteSubUserHandler(serverCtx),
				},
				{
					// 废弃子用户
					Method:  http.MethodPost,
					Path:    "/deprecated",
					Handler: DeprecatedSubUserHandler(serverCtx),
				},
				{
					// 编辑用户的流量配额与带宽限制
					Method:  http.MethodPost,
					Path:    "/edit",
					Handler: EditSubUserLimitHandler(serverCtx),
				},
				{
					// 拉取子用户列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: ListSubUserHandler(serverCtx),
				},
				{
					// 获取废弃的子用户列表
					Method:  http.MethodGet,
					Path:    "/list-deprecated",
					Handler: ListDeprecatedSubUserHandler(serverCtx),
				},
				{
					// 拉取pops列表
					Method:  http.MethodGet,
					Path:    "/pops",
					Handler: ListPopsHandler(serverCtx),
				},
				{
					// 获取总的配额
					Method:  http.MethodGet,
					Path:    "/total-quota",
					Handler: GetTotalQuotaHandler(serverCtx),
				},
				{
					// 更新子账户状态
					Method:  http.MethodPost,
					Path:    "/update-status",
					Handler: UpdateSubUserStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/subuser"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Header, serverCtx.UserAgent, serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/all-Day",
					Handler: GetAllStatsPerDayHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/all-hour",
					Handler: GetAllStatsPerHourHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/all-minute",
					Handler: GetAllStatsPer5MinHandler(serverCtx),
				},
				{
					// 获取子账号资源使用情况
					Method:  http.MethodGet,
					Path:    "/subuser-usage",
					Handler: GetSubUserUsageHandler(serverCtx),
				},
				{
					// 获取统计概要
					Method:  http.MethodGet,
					Path:    "/summary",
					Handler: GetStatSummaryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user-day",
					Handler: GetUserStatsPerDayHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user-hour",
					Handler: GetUserStatsPerHourHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user-minute",
					Handler: GetUserStatsPer5MinHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/stat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Header, serverCtx.UserAgent},
			[]rest.Route{
				{
					// 登陆
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: auth.LoginHandler(serverCtx),
				},
				{
					// 谷歌登陆
					Method:  http.MethodPost,
					Path:    "/login-by-google",
					Handler: auth.LoginByGoogleHandler(serverCtx),
				},
				{
					// 刷新令牌
					Method:  http.MethodPost,
					Path:    "/refresh-token",
					Handler: auth.RefreshTokenHandler(serverCtx),
				},
				{
					// 注册账号
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: auth.RegisterHandler(serverCtx),
				},
				{
					// 重设密码
					Method:  http.MethodPost,
					Path:    "/reset-password",
					Handler: auth.ResetPasswordHandler(serverCtx),
				},
				{
					// 发送验证码
					Method:  http.MethodPost,
					Path:    "/send-email-code",
					Handler: auth.SendEmailCodeHandler(serverCtx),
				},
				{
					// test
					Method:  http.MethodGet,
					Path:    "/test",
					Handler: auth.TestHandler(serverCtx),
				},
				{
					// 账号是否注册
					Method:  http.MethodPost,
					Path:    "/user-exists",
					Handler: auth.UserExistsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/auth"),
	)
}
