// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	auth "titan-ipweb/internal/handler/auth"
	"titan-ipweb/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Header, serverCtx.UserAgent, serverCtx.Auth},
			[]rest.Route{
				{
					// 创建socks5用户
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: CreateSubUserHandler(serverCtx),
				},
				{
					// 删除socks5用户
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: DeleteSubUserHandler(serverCtx),
				},
				{
					// 拉取socks5用户列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: ListSubUserHandler(serverCtx),
				},
				{
					// 拉取pops列表
					Method:  http.MethodGet,
					Path:    "/pops",
					Handler: ListPopsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/subuser"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Header, serverCtx.UserAgent},
			[]rest.Route{
				{
					// 登陆
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: auth.LoginHandler(serverCtx),
				},
				{
					// 谷歌登陆
					Method:  http.MethodPost,
					Path:    "/login-by-google",
					Handler: auth.LoginByGoogleHandler(serverCtx),
				},
				{
					// 刷新令牌
					Method:  http.MethodPost,
					Path:    "/refresh-token",
					Handler: auth.RefreshTokenHandler(serverCtx),
				},
				{
					// 注册账号
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: auth.RegisterHandler(serverCtx),
				},
				{
					// 重设密码
					Method:  http.MethodPost,
					Path:    "/reset-password",
					Handler: auth.ResetPasswordHandler(serverCtx),
				},
				{
					// 发送验证码
					Method:  http.MethodPost,
					Path:    "/send-email-code",
					Handler: auth.SendEmailCodeHandler(serverCtx),
				},
				{
					// test
					Method:  http.MethodGet,
					Path:    "/test",
					Handler: auth.TestHandler(serverCtx),
				},
				{
					// 账号是否注册
					Method:  http.MethodPost,
					Path:    "/user-exists",
					Handler: auth.UserExistsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/auth"),
	)
}
