// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package ippmclient

type AddBlackListReq struct {
	NodeID string `json:"node_id"`
}

type AllStatsPer5MinReq struct {
	PopID   string `form:"popid"`
	Minutes int32  `form:"minutes"`
}

type AllStatsPerDayReq struct {
	PopID string `form:"popid"`
	Days  int32  `form:"days"`
}

type AllStatsPerHourReq struct {
	PopID string `form:"popid"`
	Hours int32  `form:"hours"`
}

type CreateUserReq struct {
	UserName          string        `json:"user_name"`
	Password          string        `json:"password"`
	PopId             string        `json:"pop_id"`
	TrafficLimit      *TrafficLimit `json:"traffic_limit,optional"`
	Route             *Route        `json:"route,optional"`
	UploadRateLimit   int64         `json:"upload_rate_limit,default=655360"`
	DownloadRateLimit int64         `json:"download_rate_limit,default=1310720"`
}

type CreateUserResp struct {
	UserName     string        `json:"user_name"`
	PopId        string        `json:"pop_id"`
	TrafficLimit *TrafficLimit `json:"traffic_limit"`
	Route        *Route        `json:"route"`
	NodeIP       string        `json:"node_ip"`
}

type DeleteUserReq struct {
	UserName string `json:"user_name"`
}

type GetAuthTokenResp struct {
	Token string `json:"token"`
}

type GetBlackListReq struct {
	PodID string `form:"popid"`
}

type GetBlackListResp struct {
	Nodes []string `json:"nodes"`
}

type GetNodePopReq struct {
	NodeId string `form:"nodeid"`
}

type GetNodePopResp struct {
	ServerURL   string `json:"server_url"`
	AccessToken string `json:"access_token"`
}

type GetPopsResp struct {
	Pops []*Pop
}

type GetUserReq struct {
	UserName string `form:"username"`
}

type GetUserResp struct {
	User
	PopId string `json:"pop_id"`
}

type KickNodeReq struct {
	NodeID string `form:"nodeid"`
}

type ListNodeReq struct {
	PopID string `form:"popid"`
	Type  int    `form:"type"`
	Start int    `form:"start"`
	End   int    `form:"end"`
}

type ListNodeResp struct {
	Nodes []*Node `json:"nodes"`
	Total int     `json:"total"`
}

type ListUserReq struct {
	PopID string `form:"popid"`
	Start int    `form:"start"`
	End   int    `form:"end"`
}

type ListUserResp struct {
	Users []*User `json:"users"`
	Total int     `json:"total"`
}

type ModifyUserPasswordReq struct {
	UserName    string `json:"user_name"`
	NewPassword string `json:"new_password"`
}

type ModifyUserReq struct {
	UserName     string        `json:"user_name"`
	TrafficLimit *TrafficLimit `json:"traffic_limit,optional"`
	Route        *Route        `json:"route,optional"`
}

type Node struct {
	Id       string `json:"id"`
	IP       string `json:"ip"`
	NetDelay int    `json:"net_delay"`
	BindUser string `json:"bind_user"`
	Online   bool   `json:"online"`
}

type Pop struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	Area            string `json:"area"`
	Socks5Addr      string `json:"socks5_addr"`
	TotalNode       int    `json:"total_node"`
	OnlineNodeCount int    `json:"online_node_count"`
	CountryCode     string `json:"country_code"`
}

type RemoveBlackListReq struct {
	NodeID string `json:"node_id"`
}

type Route struct {
	Mode            int    `json:"mode"`
	NodeID          string `json:"node_id,optional"`
	IntervalMinutes int    `json:"interval_minutes,optional"`
	UtcMinuteOfDay  int    `json:"utc_minute_of_day,optional"`
}

type StartOrStopUserReq struct {
	UserName string `json:"user_name"`
	Action   string `json:"action"`
}

type StatPoint struct {
	Timestamp int64 `json:"timestamp"`
	Bandwidth int64 `json:"bandwidth"`
	Traffic   int64 `json:"traffic'`
}

type StatsResp struct {
	Stats []*StatPoint `json:"stats"`
}

type SwitchUserRouteNodeReq struct {
	UserName string `json:"user_name"`
	NodeId   string `json:"node_id, optional"`
}

type TrafficLimit struct {
	StartTime    int64 `json:"start_time"`
	EndTime      int64 `json:"end_time"`
	TotalTraffic int64 `json:"total_traffic,default=1073741824000"`
}

type User struct {
	UserName            string        `json:"user_name"`
	TrafficLimit        *TrafficLimit `json:"traffic_limit"`
	Route               *Route        `json:"route"`
	NodeIP              string        `json:"node_ip"`
	NodeOnline          bool          `json:"node_online"`
	CurrentTraffic      int64         `json:"current_traffic"`
	Off                 bool          `json:"off"`
	UploadRateLimit     int64         `json:"upload_rate_limit"`
	DownloadRateLimit   int64         `json:"download_rate_limit"`
	LastRouteSwitchTime int64         `json:"last_route_switch_time"`
}

type UserOperationResp struct {
	Success bool   `json:"success"`
	ErrMsg  string `json:"err_msg"`
}

type UserStats5PerMinReq struct {
	Username string `form:"username"`
	Minutes  int32  `form:"minutes"`
}

type UserStatsPerDayReq struct {
	Username string `form:"username"`
	Days     int32  `form:"days"`
}

type UserStatsPerHourReq struct {
	Username string `form:"username"`
	Hours    int32  `form:"hours"`
}
